#!/usr/bin/env ruby
require 'net/http'

loop do
  begin
    uri = URI.parse 'http://neo4j:7474'
    resp = Net::HTTP.get uri
  rescue SocketError => se
    puts se
    sleep 0.5
    next
  rescue Exception => e
    puts e
    sleep 0.5
    next
  end

  puts 'It works!'
  system ARGV.join(' ')
  exit
end
